### ISSUE TITLE
User Story 5: Edit Room

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#11]
## Value proposition

As a user
I want to edit a room
in order to update the name or room type

## Description
![user-story-6_edit-room](https://github.com/HenrikeStahlhut/capstone-project/assets/126799897/03c96296-2207-4aac-9991-f16f15dceed8)

## Acceptance criteria

- [ ] On the room detail page, a button to edit the room is displayed
- [ ] if the button is clicked, a modal opens with a form to edit the room's name and room type
- [ ] a button to cancel is displayed
- [ ] a button to save the changes is displayed 
- [ ] the background gets blurred if the modal is opend 

## Tasks

- [ ] create new feature branch 
- [ ] add edit room modal component
- [ ] add icon to edit 

Size: M

**Comment by t0bbl** [comment]
lgtm
