### ISSUE TITLE
User Story 6: Delete Room

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#14]
## Value proposition

As a user
I want to delete rooms
if i don't need them anymore, without deleting the plants. 

## Description
![user-story-6_delete-room](https://github.com/HenrikeStahlhut/capstone-project/assets/126799897/b0b02739-3c83-48dc-afaa-78bf2500096e)

## Acceptance criteria

- [ ] On the room detail page, a button to delete the room is displayed
- [ ] if the button is clicked, an alert opens where the user has to confirm they want to delete the room
- [ ] if the room is deleted, the plants in this room don't get deleted 

## Tasks

- [ ] create new feature branch 
- [ ] add delete room modal component
- [ ] add icon to delete 

Size: S

**Comment by cmgoersch** [comment]
Well described and doable! Have fun and success. Released from my side.
