### ISSUE TITLE
User Story 8: Homepage - room overview

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#16]
## Value proposition

As a user
I want to have a homepage
so i have a overview of all features like my rooms

## Description
![user-story-8_homepage-rooms](https://github.com/HenrikeStahlhut/capstone-project/assets/126799897/9c485ab3-38da-487f-8247-06df8c4d324e)

## Acceptance criteria

- [ ] a greeting is displayed, e.g. "Good Morning, user!"
- [ ] a card with room tiles as a preview is displayed
- [ ] the card has a headline reading "My rooms" 
- [ ] in the navigation, an additional "home" button is displayed
- [ ] clicking the your rooms card navigates the user to the room overview page 

## Tasks

- [ ] create new feature branch 
- [ ] add new page for homepage
- [ ] create components

Size: S

**Comment by doctype-Melvin** [comment]
LGTM!
Let's go!
