### ISSUE TITLE
User Story 9: Homepage - plants overview 

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#17]
## Value proposition

As a user
I want to have a homepage
so i have a overview of all features like my plants

## Description
![user-story-9_homepage-plants](https://github.com/HenrikeStahlhut/capstone-project/assets/126799897/fb599357-d698-445d-b0a7-cbdddc50b2ac)

## Acceptance criteria

- [ ] a greeting is displayed, e.g. "Good Morning, user!"
- [ ] a card with room tiles as a preview is displayed
- [ ] a card with plant tiles as a preview is displayed
- [ ] the card has a headline reading "My rooms" 
- [ ] the card has a headline reading "My plants" 
- [ ] in the navigation, an additional "home" button is displayed
- [ ] clicking the your rooms and plants card navigates the user to the respective page 

## Tasks

- [ ] create new feature branch 
- [ ] create components

Size: S
