### ISSUE TITLE
User story 1: All rooms list

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#2]
## Value proposition

As a user
I want a list of all my rooms 
So i have an overview of all the rooms my plants are in

## Description
![user-story-1](https://user-images.githubusercontent.com/126799897/236133366-58a621c6-cac5-446a-8bf8-718ba00dfb75.png)

## Acceptance criteria

- [ ] all rooms are displayed as a list 
- [ ] each rooms picture is displayed 
- [ ] each rooms name is displayed below the picture 
- [ ] a headline which says "My Rooms" is displayed 

## Tasks

- [ ] create a new branch 
- [ ]  define Global Styles
- [ ] create room component
- [ ] create room page
- [ ] create header component
- [ ] create an example db with rooms

Size: M

**Comment by BenRodProd** [comment]
LGTM

**Comment by mbosselmann** [comment]
Hi Henny,
you rock! 🪨 Even though Ben left you an approval I want to add my remarks to your first user story:

## Value Proposition

- it is enough to write "as a user". you do not need to add "who tracks their plants in their apartment"

## Description
- your description shows parts of your app that you do not implement in this state yet: the back link and the navigation
- they should be visible later when you need them :)

## Acceptance criteria
- your wireframe and your acceptance criteria do not match:
  - "a headline which says "Your Rooms" is displayed" - your description has the title "Rooms" I would also recommend that the title is "My Rooms" as the user does not want to see the rooms of another person.
  - "each rooms name is displayed below the picture" the name of each room is missing in your wireframe :)

And if you do not want to set a size for your user story (this is optional) then you can remove this part. With size you can decide what you think is the complexity of your user story (usually small, medium or large).

I hope this does help! Feel free to ask if you have questions. :)

**Comment by HenrikeStahlhut** [comment]
Thanks @ Mareike for the review! I edited my user story, so hopefully its good to go now :)

**Comment by JessicaLoers** [comment]
**Hey @HenrikeStahlhut** ✌️
This is a really good user story. I saw that you took Mareike's suggestions into account. 

I only noticed one tiny little thing:
The headline in the wireframe is _"My Rooms"_. In the _"Acceptance Criteria"_ it still says "Your Rooms". You should change that to _"My Rooms"_. 

The US is approved, but it would be important that you correct this note above. 🙂

**Comment by HenrikeStahlhut** [comment]
Hey @JessicaLoers, 
thanks for the review! I totally forgot to edit the description, thanks for pointing that out 👀
I'll correct it now 😁
