### ISSUE TITLE
User Story 10: Update plants

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#23]
## Value proposition

As a user
I want to edit plants
in order to update my plants

## Description
If a user clicks on a plant, the detail page opens where the user can edit the Plants name. 

## Acceptance criteria

- [ ] the plants name is displayed
- [ ] a button to edit the plant is displayed
- [ ] if the user clicks the button, a modal to edit the plant opens 

## Tasks

- [ ] create new branch 
- [ ] create new modal 

Size: M

**Comment by antoniatandler** [comment]
sounds good to me! 😇
