### ISSUE TITLE
US 11: Plant Detail page 

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#29]
## Value proposition

As a user
I want to have a detail page
in order to see details about my plant

## Acceptance criteria

- [ ] the plants name is displayed
- [ ] the plants room is displayed
- [ ] the plants type is displayed
- [ ] nav is there 
- [ ] header is there 
- [ ] you can update plant

## Tasks

- [ ] try not to cry 

Size: S
