### ISSUE TITLE
User Story 4: Overview of plants in room

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#3]
## Value proposition

As a user
I want to have a list of all plants in one room
so that i have an overview which plants are in that respective room

## Description
![user-story-4_Plants-in-Room](https://github.com/HenrikeStahlhut/capstone-project/assets/126799897/adef8631-f260-457f-b238-9c0ae42dcb86)

## Acceptance criteria

- [ ] a button to go back is displayed, so the user can navigate back to the room overview
- [ ] a headline which says the name of the respective room is displayed
- [ ] all plants in that room are displayed as a list
- [ ] each plants name is displayed

## Tasks

- [ ] create new feature branch
- [ ] create page where each rooms plants are displayed
- [ ] create card component for every plant 
- [ ] create list where plants in respective room are displayed
- [ ] create back button component 
- [ ] allow the user to go back forth between the two pages

Size: M

**Comment by CJAkkuec** [comment]
LGTM 🚀
