### ISSUE TITLE
User story 3: Add Plants Page

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#4]
## Value proposition

As a user
I want to add plants 
to personalize my app with plants i have in my home

## Description
![user-story-3_addPlants](https://user-images.githubusercontent.com/126799897/236414604-329cc0ed-4b88-4339-9b3f-25def804580b.png)

## Acceptance criteria
- [ ] a header that says "Add Plant" is displayed
- [ ] a navigation bar is displayed, where the user navigates to the "Add Plant" page
- [ ] in the navigation, an add icon is displayed
- [ ] below the add icon is a label/name "Add" displayed
- [ ] a button which says "I want to add my own plant" is displayed

### Add own plant: 
- [ ] A button to go back to the last page is displayed
- [ ] a header that says "Add your own plant" is displayed
- [ ] an input field for the name is displayed
- [ ] a  dropdown menu to choose which room your plant stands in is displayed
- [ ] a button for adding the plant is displayed

## Tasks

- [ ] create new feature branch 
- [ ] create navigation component
- [ ] add link to "Add Plant" Page
- [ ] add icon
- [ ] style navigation 
- [ ] append navigation to every page of the app
- [ ] create button component for add buttons
- [ ] create form component

Size: L

**Comment by mulewile** [comment]
This looks good. I guess the home button/icon links to the plants overview of which you mentioned in your tasks.

> add links to respective pages.

Just wondering if the add and toDo links are already leading the user to existing pages. If not, I would suggest you work on one link and the linked page as one user story. For example the add button could lead the user to a form and I would say this could be one user story...add link + form/linked page. The the toDo link + the linked page as another user story.

**Comment by HenrikeStahlhut** [comment]
@mulewile great suggestion, i didn't think about that! 
I thought i'd do the navigation first and then the home/add/todo page, but your technique is was easier. Thanks 😄

**Comment by HenrikeStahlhut** [comment]
Thanks to earlier suggestions, I changed my **US from just the navigation, to an "Add Plants Page"** with the navigation. 
I'll continue to add navigation links as I go further on in my app and create more pages such as home or todo. 

**Heres the old US as reference:** 

> 
> ### Value proposition
> 
> As a user
> I want to have a navigation bar
> in order to navigate through the app
> 
> ### Description
> (old wireframe here)
> 
> ### Acceptance criteria
> 
> - [ ] a navigation bar is displayed
> - [ ] a home icon is displayed
> - [ ] an add icon is displayed
> - [ ] a todo icon is displayed
> - [ ] each navigation icon has a label/name underneath
> 
> ## Tasks
> 
> - [ ] create new feature branch 
> - [ ] create navigation component
> - [ ] add links to respective pages
> - [ ] add icons 
> - [ ] style navigation 
> - [ ] append navigation to every page of the app
> 
> Size: S
>

**Comment by mbosselmann** [comment]
Hi Henny,
good job! 👍 But I have a general remark about your user story:

- if I understand your user story correctly the user cannot add a plant yet as this user story is only for adding the page but not the form
- as William suggested and as your value proposition also implies, you should also add the form and the form handling in this user story 

I hope this does help! Feel free to ask me if you have further questions. :)

**Comment by HenrikeStahlhut** [comment]
Hi Mareike, 
thanks for the review! I tried to implement yours and William's suggestions the best i could. I hope you understand where i'm coming from. 

I wanted to have a general adding page, which has a button and later on a search function to add plants from the api. If you click the button to add your own plant, you get redirected to the "add your own plant" page. I hope the changes are now clear and make sense :)
