### ISSUE TITLE
User Story 2: Add Room 

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#7]
## Value proposition

As a user
I want to add my own rooms
in order to customize my app 

## Description
![user-story-2_addRoom](https://user-images.githubusercontent.com/126799897/236522972-61b1b3c9-3df0-4186-89a7-29a97f7968fe.png)

## Acceptance criteria

- [ ] A button to add rooms is displayed in the Header of the rooms page
- [ ] clicking the button triggers a modal/pop up window with the "Add room" Form 
- [ ] the modal has a heading that says "Add room"
- [ ] the modal form has an input field to give your room a name 
- [ ] the modal form has a dropdown menu to chose your room's type (e.g. living room) which assigns a picture to the room based on its type 
- [ ] the modal form has a button that adds the new room to the room overview
- [ ] the modal has a cancel button in the form of an x 
- [ ] the modal is closed when the button is clicked

## Tasks
- [ ] create new feature branch
- [ ] create modal 
- [ ] write logic to add the users room to the room overview page
- [ ] style modal
- [ ] store room in localstorage

Size: M
