### ISSUE TITLE
User Story 7: All Plants Overview

### ISSUE THREAD

**Issue by HenrikeStahlhut** [HenrikeStahlhut/capstone-project#8]
## Value proposition

As a user
I want to have a list of all my plants
to get an overview

## Description
![user-story-5_AllPlantsOverview](https://user-images.githubusercontent.com/126799897/236559933-75c816cc-035d-4a58-a54b-a64027ac6717.png)

## Acceptance criteria

- [ ] a button to go back is displayed, so the user can navigate back to the last page
- [ ] a headline which says "Your Garden" is displayed
- [ ] all plants the user previously added are displayed as a list
- [ ] each plants name is displayed
- [ ] each plants location is displayed
- [ ] each plants picture is displayed

## Tasks

- [ ] create new feature branch
- [ ] create page where all plants are displayed 
- [ ] create card component for every plant 
- [ ] create list where all plants are displayed
- [ ] add back button
- [ ] add logic for adding plant to this page via "add plant"

Size: L
